### ISSUE TITLE
README

### ISSUE THREAD

**Issue by matthew4444** [PocketSoftMine/SoftMine#3]
move this project to gladiatormine plz

**Comment by matthew4444** [comment]
http://github.com/endermaniacskingdom/gladiatormine/

**Comment by marcosvkp** [comment]
Sorry, project is independent

**Comment by matthew4444** [comment]
kk

**Comment by matthew4444** [comment]
can i be a pocketsoft member plz?

**Comment by matthew4444** [comment]
can i be a pocketsoft member plz?
